name: web-api-gateway
language: Python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: website-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
